import UploadForm from "@/components/upload-form"

export default function UploadPreviewSection() {
    return (
        <section className="py-20 bg-white">
            <div className="container mx-auto px-4">
                <div className="max-w-4xl mx-auto">
                    <div className="text-center mb-12">
                        <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-6">See The Potential</h2>
                        <p className="text-lg text-slate-700 max-w-2xl mx-auto">
                            Upload a photo of your space to see a redesigned version generated by our AI.
                        </p>
                    </div>
                    <UploadForm />
                </div>
            </div>
        </section>
    )
}
